var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled from "styled-components";
export var FormWrapper = styled.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  display: flex;\n  flex-direction: column;\n  justify-content: center;\n  width: 100%;\n"], ["\n  display: flex;\n  flex-direction: column;\n  justify-content: center;\n  width: 100%;\n"])));
export var FormElement = styled.div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  display: flex;\n  flex-direction: column;\n  justify-content: center;\n  width: 100%;\n  min-height: 80px;\n  padding: 5px;\n  .form-title{\n    color: #708090;\n    padding-bottom: 5px;\n    font-weight: 600;\n  }\n  label {\n    color: #708090;\n    padding-bottom: 5px;\n  }\n  span{\n    color: #ff0000;\n    margin-left:5px\n  }\n  i {\n    color: #708090;\n    font-size: 14px;\n    letter-spacing: 1px;\n    padding-bottom: 2px;\n  }\n  .form-text{\n    display: flex;\n    width: 100%;\n    align-items: center;\n    justify-content: space-between;\n    height: 40px;\n    border: 1px solid #708090;\n    border-radius: 5px;\n    padding-left: 10px;\n  }\n  .form-control-text{\n    flex: 10;\n    border:none;\n    &:focus {\n      outline: none !important;\n    }\n  }\n  .form-control {\n    border: 1px solid #708090;\n    height: 40px;\n    width:100%;\n    border-radius: 5px;\n    padding-left: 10px;\n    &:focus {\n      outline: none !important;\n    }\n  }\n  .form-password{\n    padding:5px;\n    width:25px;\n    &:hover{\n      cursor:pointer\n    }\n  }\n  .form-error {\n    font-size: 12px;\n    letter-spacing: 1px;\n    margin-top: 5px;\n    color: #ff0000;\n  }\n"], ["\n  display: flex;\n  flex-direction: column;\n  justify-content: center;\n  width: 100%;\n  min-height: 80px;\n  padding: 5px;\n  .form-title{\n    color: #708090;\n    padding-bottom: 5px;\n    font-weight: 600;\n  }\n  label {\n    color: #708090;\n    padding-bottom: 5px;\n  }\n  span{\n    color: #ff0000;\n    margin-left:5px\n  }\n  i {\n    color: #708090;\n    font-size: 14px;\n    letter-spacing: 1px;\n    padding-bottom: 2px;\n  }\n  .form-text{\n    display: flex;\n    width: 100%;\n    align-items: center;\n    justify-content: space-between;\n    height: 40px;\n    border: 1px solid #708090;\n    border-radius: 5px;\n    padding-left: 10px;\n  }\n  .form-control-text{\n    flex: 10;\n    border:none;\n    &:focus {\n      outline: none !important;\n    }\n  }\n  .form-control {\n    border: 1px solid #708090;\n    height: 40px;\n    width:100%;\n    border-radius: 5px;\n    padding-left: 10px;\n    &:focus {\n      outline: none !important;\n    }\n  }\n  .form-password{\n    padding:5px;\n    width:25px;\n    &:hover{\n      cursor:pointer\n    }\n  }\n  .form-error {\n    font-size: 12px;\n    letter-spacing: 1px;\n    margin-top: 5px;\n    color: #ff0000;\n  }\n"])));
export var ButtonContainer = styled.div(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n    display: flex;\n    align-items: center;\n    justify-content: center;\n    width: 100%;\n"], ["\n    display: flex;\n    align-items: center;\n    justify-content: center;\n    width: 100%;\n"])));
export var SubmitButton = styled.button(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n    width: ", " ;\n    height: ", " ;\n    background-color:", " ;\n    font-weight: ", ";\n    font-size:", ";\n    color:", ";\n    letter-spacing: 2px;\n    border-radius: 5px;\n    border: none;\n    &:hover{\n        cursor:pointer;\n        letter-spacing: 3px;\n    }\n    &:active {\n        transform: scale(0.98);\n        box-shadow: 3px 2px 22px 1px rgba(0, 0, 0, 0.24);\n    }\n"], ["\n    width: ", " ;\n    height: ", " ;\n    background-color:", " ;\n    font-weight: ", ";\n    font-size:", ";\n    color:", ";\n    letter-spacing: 2px;\n    border-radius: 5px;\n    border: none;\n    &:hover{\n        cursor:pointer;\n        letter-spacing: 3px;\n    }\n    &:active {\n        transform: scale(0.98);\n        box-shadow: 3px 2px 22px 1px rgba(0, 0, 0, 0.24);\n    }\n"])), function (props) { var _a; return ((_a = props === null || props === void 0 ? void 0 : props.style) === null || _a === void 0 ? void 0 : _a.width) || '30%'; }, function (props) { var _a; return ((_a = props === null || props === void 0 ? void 0 : props.style) === null || _a === void 0 ? void 0 : _a.height) || '35px'; }, function (props) { var _a; return ((_a = props === null || props === void 0 ? void 0 : props.style) === null || _a === void 0 ? void 0 : _a.backgroundColor) || '#60A728'; }, function (props) { var _a; return ((_a = props === null || props === void 0 ? void 0 : props.style) === null || _a === void 0 ? void 0 : _a.fontWeight) || "600"; }, function (props) { var _a; return ((_a = props === null || props === void 0 ? void 0 : props.style) === null || _a === void 0 ? void 0 : _a.fontSize) || '#16px'; }, function (props) { var _a; return ((_a = props === null || props === void 0 ? void 0 : props.style) === null || _a === void 0 ? void 0 : _a.color) || '#fff'; });
var templateObject_1, templateObject_2, templateObject_3, templateObject_4;
